#!/usr/bin/env bash

set -euo pipefail

: "${WOW_HOME:=$HOME/.local/share/wow}"
: "${WOW_API_REPO:=https://github.com/Ketho/vscode-wow-api}"
: "${WOW_API_BRANCH:=master}"
: "${WOW_UI_SOURCE_REPO:=https://github.com/Gethe/wow-ui-source}"
: "${WOW_UI_SOURCE_BRANCH:=live}"
: "${WOW_RESOURCES_URL:=https://raw.githubusercontent.com/Ketho/BlizzardInterfaceResources/live/Resources}"
: "${LUACHECK_DEFAULT_CONFIG:=${XDG_CONFIG_HOME:-$HOME/.config}/luacheck/.luacheckrc}"

log() { printf 'wow-setup: %s\n' "$1" >&2; }

# Shallow clone on first run, fast-forward afterwards; a failed update keeps the old checkout.
checkout() {
  local repo=$1 branch=$2 dir=$3
  if [ -d "$dir/.git" ]; then
    if git -C "$dir" fetch -q --depth 1 origin "$branch"; then
      git -C "$dir" reset -q --hard FETCH_HEAD
    else
      log "update of $dir failed, keeping $(git -C "$dir" rev-parse --short HEAD)"
    fi
  else
    rm -rf "$dir"
    git clone -q --depth 1 -b "$branch" "$repo" "$dir"
  fi
  log "$dir at $(git -C "$dir" rev-parse --short HEAD)"
}

# Generated lists of every Blizzard global on live; a failed download keeps the previous copy.
fetch_resources() {
  local dir=$1 file
  for file in FrameXML.lua Frames.lua GlobalAPI.lua GlobalStrings/enUS.lua; do
    mkdir -p "$dir/$(dirname "$file")"
    if curl -fsSL --retry 2 "$WOW_RESOURCES_URL/$file" -o "$dir/$file.tmp"; then
      mv "$dir/$file.tmp" "$dir/$file"
    else
      rm -f "$dir/$file.tmp"
      log "download of $file failed, keeping the previous copy"
    fi
  done
}

resource_globals() {
  local dir=$1
  [ -d "$dir" ] || return 0
  for f in "$dir/FrameXML.lua" "$dir/Frames.lua" "$dir/GlobalAPI.lua"; do
    [ -f "$f" ] && sed -n -E 's/^[[:space:]]*"([A-Za-z_][A-Za-z0-9_]*)[".].*/\1/p' "$f"
  done
  if [ -f "$dir/GlobalStrings/enUS.lua" ]; then
    sed -n -E 's/^_G\["([A-Za-z_][A-Za-z0-9_]*)"\].*/\1/p; s/^([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*=.*/\1/p' "$dir/GlobalStrings/enUS.lua"
  fi
}

# Every top-level name the WoW API annotations define, plus Blizzard's generated global lists, becomes a luacheck read-only global.
write_luacheckrc() {
  local annotations=$1 out=$2 resources=${3:-}
  mkdir -p "${out%/*}"
  {
    printf -- '-- generated by wow-setup from %s; a .luacheckrc in the repo wins\n' "$annotations"
    printf 'std = "none"\nmax_line_length = false\nread_globals = {\n'
    {
      find "$annotations" -type f -name '*.lua' -print0 \
        | xargs -0 sed -n -E 's/^(function[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)[[:space:].(=].*/\2/p'
      resource_globals "$resources"
    } | grep -v -E '^(local|return|end|if|for|while|do|repeat|else|elseif|then|and|or|not|nil|true|false)$' \
      | sort -u | sed 's/.*/  "&",/'
    printf '}\n'
  } > "$out.tmp"
  mv "$out.tmp" "$out"
  log "$out: $(grep -c '^  "' "$out") globals"
}

main() {
  mkdir -p "$WOW_HOME"
  checkout "$WOW_API_REPO" "$WOW_API_BRANCH" "$WOW_HOME/wow-api"
  checkout "$WOW_UI_SOURCE_REPO" "$WOW_UI_SOURCE_BRANCH" "$WOW_HOME/wow-ui-source"
  [ -d "$WOW_HOME/wow-api/Annotations" ] || { log "no Annotations directory in $WOW_HOME/wow-api"; return 1; }
  fetch_resources "$WOW_HOME/resources"
  write_luacheckrc "$WOW_HOME/wow-api/Annotations" "$LUACHECK_DEFAULT_CONFIG" "$WOW_HOME/resources"
}

main "$@"
