#!/usr/bin/env bash

set -euo pipefail

: "${WOW_HOME:=$HOME/.local/share/wow}"
: "${WOW_API_REPO:=https://github.com/Ketho/vscode-wow-api}"
: "${WOW_API_BRANCH:=master}"
: "${WOW_UI_SOURCE_REPO:=https://github.com/Gethe/wow-ui-source}"
: "${WOW_UI_SOURCE_BRANCH:=live}"
: "${LUACHECK_DEFAULT_CONFIG:=${XDG_CONFIG_HOME:-$HOME/.config}/luacheck/.luacheckrc}"

log() { printf 'wow-setup: %s\n' "$1" >&2; }

# Shallow clone on first run, fast-forward afterwards; a failed update keeps the old checkout.
checkout() {
  local repo=$1 branch=$2 dir=$3
  if [ -d "$dir/.git" ]; then
    if git -C "$dir" fetch -q --depth 1 origin "$branch"; then
      git -C "$dir" reset -q --hard FETCH_HEAD
    else
      log "update of $dir failed, keeping $(git -C "$dir" rev-parse --short HEAD)"
    fi
  else
    rm -rf "$dir"
    git clone -q --depth 1 -b "$branch" "$repo" "$dir"
  fi
  log "$dir at $(git -C "$dir" rev-parse --short HEAD)"
}

# Every top-level name the WoW API annotations define becomes a luacheck read-only global.
write_luacheckrc() {
  local annotations=$1 out=$2
  mkdir -p "${out%/*}"
  {
    printf -- '-- generated by wow-setup from %s; a .luacheckrc in the repo wins\n' "$annotations"
    printf 'std = "none"\nmax_line_length = false\nread_globals = {\n'
    find "$annotations" -type f -name '*.lua' -print0 \
      | xargs -0 sed -n -E 's/^(function[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)[[:space:].(=].*/\2/p' \
      | grep -v -E '^(local|return|end|if|for|while|do|repeat|else|elseif|then|and|or|not|nil|true|false)$' \
      | sort -u | sed 's/.*/  "&",/'
    printf '}\n'
  } > "$out.tmp"
  mv "$out.tmp" "$out"
  log "$out: $(grep -c '^  "' "$out") globals"
}

main() {
  mkdir -p "$WOW_HOME"
  checkout "$WOW_API_REPO" "$WOW_API_BRANCH" "$WOW_HOME/wow-api"
  checkout "$WOW_UI_SOURCE_REPO" "$WOW_UI_SOURCE_BRANCH" "$WOW_HOME/wow-ui-source"
  [ -d "$WOW_HOME/wow-api/Annotations" ] || { log "no Annotations directory in $WOW_HOME/wow-api"; return 1; }
  write_luacheckrc "$WOW_HOME/wow-api/Annotations" "$LUACHECK_DEFAULT_CONFIG"
}

main "$@"
