#!/usr/bin/env bash
set -euo pipefail
N=22.23.2; ND=node-v22.23.2-linux-x64; NH=/opt/openhands/$ND; NA=$ND.tar.xz
U=0.12.7; UA=uv-x86_64-unknown-linux-gnu.tar.gz; UD=uv-x86_64-unknown-linux-gnu
fail(){ echo "$1" >&2; exit 1; }
rootdir(){ local s m; [ ! -L "$1" ]&&[ -d "$1" ]||fail "invalid root directory: $1"; s=$(stat -c '%U:%G %a' "$1");m=${s##* };[ "${s%% *}" = root:root ]&&((!(8#$m&0022)))||fail "unsafe root directory: $1"; }
rootfile(){ [ ! -L "$1" ]&&[ -f "$1" ]&&[ "$(stat -c '%U:%G %a' "$1")" = "root:root $2" ]||fail "invalid root file: $1"; }
dl(){ curl --fail --location --proto '=https' --tlsv1.2 --retry 3 --output "$2" "$1"; }
entry(){ printf '#!/bin/sh\nexec %s/bin/%s "$@"\n' "$NH" "$1"; }
assets(){ script_path=$(readlink -f -- "${BASH_SOURCE[0]}")||fail 'unable to resolve provisioning script'; asset_dir=$(dirname "$script_path"); config_path=$asset_dir/wsl.conf; [ ! -L "$config_path" ]&&[ -f "$config_path" ]||fail 'wsl.conf must be a regular sibling file'; }
preflight(){ local p; for p in /opt /usr/local /usr/local/bin;do rootdir "$p";done; for p in /opt/openhands "$NH" /usr/local/bin/node /usr/local/bin/npm /usr/local/bin/npx /usr/local/bin/uv /usr/local/bin/uvx;do if [ -e "$p" ]||[ -L "$p" ];then if [[ $p == /opt/* ]];then rootdir "$p";else rootfile "$p" 755;fi;fi;done; }
stage(){ nt=$(mktemp -d /opt/.openhands-node.XXXXXX);ut=$(mktemp -d); dl "https://nodejs.org/dist/v$N/SHASUMS256.txt" "$nt/s";dl "https://nodejs.org/dist/v$N/$NA" "$nt/$NA"; h=$(awk -v a="$NA" '$2==a{print; n++}END{if(n!=1)exit 1}' "$nt/s")||fail 'Node.js checksum is missing or ambiguous';printf '%s\n' "$h"|(cd "$nt"&&sha256sum -c -)||fail 'Node.js checksum verification failed';tar -xJf "$nt/$NA" --no-same-owner --no-same-permissions --touch -C "$nt" "$ND/bin/node" "$ND/bin/npm" "$ND/bin/npx" "$ND/lib/node_modules/npm";(cd "$nt/$ND"&&sha256sum bin/node lib/node_modules/npm/bin/npm-cli.js lib/node_modules/npm/bin/npx-cli.js >.openhands-sha256);install -o root -g root -m644 "$nt/$ND/.openhands-sha256" "$nt/$ND/.openhands-sha256";dl "https://github.com/astral-sh/uv/releases/download/$U/$UA.sha256" "$ut/s";dl "https://github.com/astral-sh/uv/releases/download/$U/$UA" "$ut/$UA";h=$(awk 'NF{print $1;n++}END{if(n!=1)exit 1}' "$ut/s")||fail 'uv checksum is missing or ambiguous';[[ $h =~ ^[0-9a-f]{64}$ ]]||fail 'uv checksum is invalid';printf '%s  %s\n' "$h" "$UA"|(cd "$ut"&&sha256sum -c -)||fail 'uv checksum verification failed';tar -xzf "$ut/$UA" --no-same-owner --no-same-permissions --touch -C "$ut"; }
install_tools(){ if [ -e "$NH" ]||[ -L "$NH" ];then rootdir "$NH";rootfile "$NH/.openhands-sha256" 644;(cd "$NH"&&sha256sum -c .openhands-sha256 >/dev/null)||fail 'invalid Node.js installation';cmp -s "$NH/bin/node" "$nt/$ND/bin/node"&&cmp -s "$NH/lib/node_modules/npm/bin/npm-cli.js" "$nt/$ND/lib/node_modules/npm/bin/npm-cli.js"&&cmp -s "$NH/lib/node_modules/npm/bin/npx-cli.js" "$nt/$ND/lib/node_modules/npm/bin/npx-cli.js"||fail 'foreign Node.js installation';else install -d -o root -g root -m755 /opt/openhands;mv "$nt/$ND" "$NH";fi; if [ -e /usr/local/bin/node ]||[ -L /usr/local/bin/node ];then cmp -s "$NH/bin/node" /usr/local/bin/node||fail 'foreign node entry point';else install -T -o root -g root -m755 "$NH/bin/node" /usr/local/bin/node;fi;for x in npm npx;do if [ -e /usr/local/bin/$x ]||[ -L /usr/local/bin/$x ];then cmp -s /usr/local/bin/$x <(entry "$x")||fail "foreign $x entry point";else entry "$x"|install -T -o root -g root -m755 /dev/stdin /usr/local/bin/$x;fi;done;for x in uv uvx;do if [ -e /usr/local/bin/$x ]||[ -L /usr/local/bin/$x ];then cmp -s /usr/local/bin/$x "$ut/$UD/$x"||fail "foreign $x installation";else install -T -o root -g root -m755 "$ut/$UD/$x" /usr/local/bin/$x;fi;done; }
[ "$(id -u)" -eq 0 ]||fail 'provisioning must run as root';[ "${WSL_DISTRO_NAME:-}" = openhands-worker ]||fail 'provisioning must run in openhands-worker';assets;if [ -L /etc/wsl.conf ]||[ -d /etc/wsl.conf ]||{ [ -e /etc/wsl.conf ]&&[ ! -f /etc/wsl.conf ];};then fail 'unsafe path: /etc/wsl.conf';fi;install -T -o root -g root -m644 "$config_path" /etc/wsl.conf;preflight;id agent >/dev/null 2>&1||useradd -K HOME_MODE=0700 -K UMASK=0077 --create-home --shell /bin/bash --user-group agent;for p in /home/agent/.openhands /home/agent/.claude /home/agent/.codex /home/agent/workspaces;do if [ -e "$p" ]||[ -L "$p" ];then [ ! -L "$p" ]&&[ "$(stat -c '%U:%G %a' "$p")" = 'agent:agent 700' ]||fail "invalid agent directory: $p";else runuser -u agent -- mkdir -m700 "$p";fi;done;[ "$(uname -m)" = x86_64 ]||fail 'unsupported architecture: only x86_64 is supported';DEBIAN_FRONTEND=noninteractive apt-get update;DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl xz-utils;nt=;ut=;trap 'rm -rf -- "$nt" "$ut"' EXIT;stage;install_tools
