---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Workflows validate

on:
  pull_request:
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Lint every workflow
        uses: reviewdog/action-actionlint@2085657ab2c7f48c58edcc767fba576f63bea76b # v1.77.0
        with:
          reporter: github-check
          fail_level: error
