---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Workflows validate

on:
  pull_request:
    paths:
      - .github/workflows/**

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Lint every workflow
        uses: reviewdog/action-actionlint@320fcdd9c860767cf17fab3b20e22e739d5d02b8 # v1.76.0
        with:
          reporter: github-check
          fail_level: error
